language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=1.35.8 node # temp solution till v1.35.8 is latest
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
