language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
sudo: false
before_install:
  - npm i -g npm # temp solution till --prefix gets fixed in pnpm
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
