language: node_js
node_js:
  - 12
  - 14
  - 15
sudo: false
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
