language: node_js
node_js:
  - 8
  - 12
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=next node # temp solution till v3.4.0 is latest
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
