environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 9
install:
  - ps: Install-Product node $env:nodejs_version
  - set PNPM_VERSION=1.35.8 # temp solution till v1.35.8 is latest
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - npm test
