environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 14
install:
  - ps: Install-Product node $env:nodejs_version
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - npm test
