environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10
    - nodejs_version: 12
install:
  - ps: Install-Product node $env:nodejs_version
  - set PNPM_VERSION=next # temp solution till v3.4.0 is latest
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - npm test
